
export const COUNTER_INCREMENT = '@COUNTER/INCREMENT'
export const COUNTER_DECREMENT = '@COUNTER/DECREMENT'
export const COUNTER_DOUBLE_INCREMENT = '@COUNTER/DOUBLE_INCREMENT'
export const COUNTER_DOUBLE_DECREMENT = '@COUNTER/DOUBLE_DECREMENT'
export const COUNTER_RESET = '@COUNTER/RESET'
export const COUNTER_RANDOM = '@COUNTER/RANDOM'
